Training:
    asynchronous: False     # Evaluate policy in asynchronous mode
    max_iterations: 10000   # Maximum iterations for updating value function
    discount: 0.9           # Discount factor for future returns
    tolerance: 0.01         # Tolerance for updating value function
